### ISSUE TITLE
Head and Neck RE4R

### ISSUE THREAD

**Issue by winchesterpro5** [Backporter/PS4-RE-TEX#2]
Hi, how to fix this crap [https://pixeldrain.com/u/F3VfQcpV](url)

**Comment by Backporter** [comment]
what?

**Comment by Backporter** [comment]
ill leave this up for one more day, if no response is posted ill close it.

**Comment by LQLLNX** [comment]
The conversion is complete, but a lot of mods lose maps and textures change.

**Comment by LQLLNX** [comment]
You can try this MOD, https://www.playground.ru/resident_evil_4/file/resident_evil_4_remake_bikini_dlya_eshli_1_1-1616194

**Comment by LQLLNX** [comment]
Every MOD author is different and the tiles they use are different but I looked at the converter code and there were only 28 and 30 tiles in it。Version number of Resident Evil 4 is 36 and 10
