### ISSUE TITLE
unable to Convert mmtr files

### ISSUE THREAD

**Issue by Deam0ncyb0rg** [Backporter/PS4-RE-TEX#3]
Game (CE-34878-0) crashes when trying to load mods with .mmtr files in it

**Comment by bara9880** [comment]
Follow this video carefully: 

> https://youtu.be/JnJ2ZWxjzz4

**Comment by Deam0ncyb0rg** [comment]
I only tried to convert resident evil 2 and 3.
So when I delete hair.mmtr.1808160001 with file related to hair. mods work fine without modded hair
